# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='short_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
