# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backlogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('short_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('who', models.CharField(blank=True, max_length=255)),
                ('what', models.CharField(blank=True, max_length=255)),
                ('why', models.CharField(blank=True, max_length=255)),
                ('accptance_criteria', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('story_points', models.IntegerField(blank=True, null=True)),
                ('business_value', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backlogs.Backlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backlog Item',
                'verbose_name_plural': 'Backlog Items',
            },
        ),
    ]
