# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog_items', '0003_backlogitem_backlog_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backlogitem',
            name='short_id',
        ),
    ]
