# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('backlog_items', '0005_backlogitem_list_ui_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogitem',
            name='parent_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
            preserve_default=False,
        ),
    ]
