# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog_items', '0006_backlogitem_parent_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogitem',
            name='parent_uuid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
