# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog_items', '0007_auto_20160427_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlogitem',
            name='is_archive',
            field=models.BooleanField(default=True),
        ),
    ]
